package pojo;
// Generated Mar 29, 2015 9:06:17 PM by Hibernate Tools 4.3.1



/**
 * AddUser generated by hbm2java
 */
public class AddUser  implements java.io.Serializable {


     private Integer id;
     private User userBySenderId;
     private User userByReceiverId;
     private String mess;

    public AddUser() {
    }

    public AddUser(User userBySenderId, User userByReceiverId, String mess) {
       this.userBySenderId = userBySenderId;
       this.userByReceiverId = userByReceiverId;
       this.mess = mess;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserBySenderId() {
        return this.userBySenderId;
    }
    
    public void setUserBySenderId(User userBySenderId) {
        this.userBySenderId = userBySenderId;
    }
    public User getUserByReceiverId() {
        return this.userByReceiverId;
    }
    
    public void setUserByReceiverId(User userByReceiverId) {
        this.userByReceiverId = userByReceiverId;
    }
    public String getMess() {
        return this.mess;
    }
    
    public void setMess(String mess) {
        this.mess = mess;
    }




}


