package pojo;
// Generated Mar 29, 2015 9:06:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChatUser generated by hbm2java
 */
public class ChatUser  implements java.io.Serializable {


     private Integer id;
     private User userByRecieverId;
     private User userBySenderId;
     private Date date;
     private String message;

    public ChatUser() {
    }

    public ChatUser(User userByRecieverId, User userBySenderId, Date date, String message) {
       this.userByRecieverId = userByRecieverId;
       this.userBySenderId = userBySenderId;
       this.date = date;
       this.message = message;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserByRecieverId() {
        return this.userByRecieverId;
    }
    
    public void setUserByRecieverId(User userByRecieverId) {
        this.userByRecieverId = userByRecieverId;
    }
    public User getUserBySenderId() {
        return this.userBySenderId;
    }
    
    public void setUserBySenderId(User userBySenderId) {
        this.userBySenderId = userBySenderId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


