package pojo;
// Generated Mar 29, 2015 9:06:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String displayName;
     private String email;
     private String mobile;
     private String fullName;
     private String pass;
     private byte status;
     private byte[] image;
     private Set chatUsersForRecieverId = new HashSet(0);
     private Set chatUsersForSenderId = new HashSet(0);
     private Set addUsersForSenderId = new HashSet(0);
     private Set addUsersForReceiverId = new HashSet(0);

    public User() {
    }

	
    public User(String displayName, String email, String mobile, String pass, byte status) {
        this.displayName = displayName;
        this.email = email;
        this.mobile = mobile;
        this.pass = pass;
        this.status = status;
    }
    public User(String displayName, String email, String mobile, String fullName, String pass, byte status, byte[] image, Set chatUsersForRecieverId, Set chatUsersForSenderId, Set addUsersForSenderId, Set addUsersForReceiverId) {
       this.displayName = displayName;
       this.email = email;
       this.mobile = mobile;
       this.fullName = fullName;
       this.pass = pass;
       this.status = status;
       this.image = image;
       this.chatUsersForRecieverId = chatUsersForRecieverId;
       this.chatUsersForSenderId = chatUsersForSenderId;
       this.addUsersForSenderId = addUsersForSenderId;
       this.addUsersForReceiverId = addUsersForReceiverId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Set getChatUsersForRecieverId() {
        return this.chatUsersForRecieverId;
    }
    
    public void setChatUsersForRecieverId(Set chatUsersForRecieverId) {
        this.chatUsersForRecieverId = chatUsersForRecieverId;
    }
    public Set getChatUsersForSenderId() {
        return this.chatUsersForSenderId;
    }
    
    public void setChatUsersForSenderId(Set chatUsersForSenderId) {
        this.chatUsersForSenderId = chatUsersForSenderId;
    }
    public Set getAddUsersForSenderId() {
        return this.addUsersForSenderId;
    }
    
    public void setAddUsersForSenderId(Set addUsersForSenderId) {
        this.addUsersForSenderId = addUsersForSenderId;
    }
    public Set getAddUsersForReceiverId() {
        return this.addUsersForReceiverId;
    }
    
    public void setAddUsersForReceiverId(Set addUsersForReceiverId) {
        this.addUsersForReceiverId = addUsersForReceiverId;
    }




}


